export const services = [
  {
    name: "Tickets",
    icon: "/icons/service-tickets.svg",
    bg: "#E7F6EC",
    borderColor: "green-500",
    href: "tickets",
  },
  {
    name: "Check-ins",
    icon: "/icons/service-checkin.svg",
    bg: "#E3EFFC",
    borderColor: "blue-500",
    href: "check-in",
  },
  {
    name: "Speakers",
    icon: "/icons/service-speaker.svg",
    bg: "#FEF6E7",
    borderColor: "orange-500",
    href: "speakers",
  },
  {
    name: "Chat Room",
    icon: "/icons/service-chatroom.svg",
    bg: "#FFECE5",
    borderColor: "red-500",
    href: "chat",
  },
  {
    name: "Games",
    icon: "/icons/service-games.svg",
    bg: "#FEF6E7",
    borderColor: "orange-500",
    href: "games",
  },
  {
    name: "Analytics",
    icon: "/icons/service-analytics.svg",
    bg: "#FFECE5",
    borderColor: "red-500",
    href: "analytics",
  },
  {
    name: "Polls",
    icon: "/icons/service-polls.svg",
    bg: "#E7F6EC",
    borderColor: "green-500",
    href: "polls",
  },
  {
    name: "Networking",
    icon: "/icons/service-networking.svg",
    bg: "#E3EFFC",
    borderColor: "blue-500",
    href: "networking",
  },
  {
    name: "Links & Resources",
    icon: "/icons/service-links.svg",
    bg: "#F3E8FF",
    borderColor: "purple-500",
    href: "links",
  },
  {
    name: "Calendar & Reminders",
    icon: "/icons/service-calendar.svg",
    bg: "#FEF3C7",
    borderColor: "amber-500",
    href: "calendar",
  },
];
